export default {
  dataCharacter: {},
  dataAllCharacter: [],
  isLoadingGet: {},
  characterDetail: {
    first_name: "",
    last_name: "",
    phone: [],
    emails: [],
    location: "",
    character_types: [],
    favorable: null,
    disclosed_by: null,
    credibility: null,
    position: null,
    located: null,
    availability: null,
    served: null,
    value_level: null,
    relevant_level: null,
    important: null,
    key_character: null,
    relevant: null,
    legal_issues: [],
    background: null,
    tags: [],
    members: [],
  },
  dataNotes: [],
  countNotes: 0,
  dataHistories: [],
  total_histories: 0,
  isLoadingHistories: false,

  //comments
  dataComment: [],
  dataCommentFeedback: [],
  countComment: 0,
  countCommentFeedback: 0,
  actionComment: {},
  actionCommentFeedback: {},
};
